# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:18:04+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    EtcerCertificatePostRequest,
    EtcerCertificatePostResponse,
    EtcerCertificatePostResponse1,
    EtcerCertificatePostResponse2,
    EtcerCertificatePostResponse3,
    EtcerCertificatePostResponse4,
    EtcerCertificatePostResponse5,
    EtcerCertificatePostResponse6,
    GovidCertificatePostRequest,
    GovidCertificatePostResponse,
    GovidCertificatePostResponse1,
    GovidCertificatePostResponse2,
    GovidCertificatePostResponse3,
    GovidCertificatePostResponse4,
    GovidCertificatePostResponse5,
    GovidCertificatePostResponse6,
    SicerCertificatePostRequest,
    SicerCertificatePostResponse,
    SicerCertificatePostResponse1,
    SicerCertificatePostResponse2,
    SicerCertificatePostResponse3,
    SicerCertificatePostResponse4,
    SicerCertificatePostResponse5,
    SicerCertificatePostResponse6,
)

app = MCPProxy(
    description='APIs provided by Public Health Engineering Department, Haryana, Haryana.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Public Health Engineering Department, Haryana, Haryana',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/phedharyana/v3'}],
)


@app.post(
    '/etcer/certificate',
    description=""" API to verify Enlistment Certificate. """,
    tags=['certificate_creation_and_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def etcer(body: EtcerCertificatePostRequest = None):
    """
    Enlistment Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/govid/certificate',
    description=""" API to verify ID Card. """,
    tags=['certificate_creation_and_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def govid(body: GovidCertificatePostRequest = None):
    """
    ID Card
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sicer/certificate',
    description=""" API to verify Sanction Letter/ Certificate. """,
    tags=['certificate_creation_and_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def sicer(body: SicerCertificatePostRequest = None):
    """
    Sanction Letter/ Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
